siteapp/urls.py
from django.urls import path
from . import views

app_name = "siteapp"

urlpatterns =[
    path('fakulteler/', views.FakulteListView.as_view(), name="fakulte_list"),
    path('fakulteler/<str:pk>/bolumler/', views.FakulteBolumListView.as_view(), name="fakulte_bolum_list"),
    path('bolum/<str:pk>/detail', views.BolumDetailView.as_view(), name="bolum_detail"),

    path('bolumler/', views.BolumListView.as_view(), name="bolum_list"),

    path('enstituler/', views.EnstituListView.as_view(), name="enstitu_list"),
    path('enstituler/<str:pk>/anabilimdali/', views.EnstituAnabilimDaliListView.as_view(), name="enstitu_abd_list"),
    path('anabilimdali/<str:pk>/detail', views.AnabilimDaliDetailView.as_view(), name="abd_detail"),

    path('kulupler/', views.KulupListView.as_view(), name="kulup_list"),
    path('kulup/<str:pk>/detail', views.KulupDetailView.as_view(), name="kulup_detail"),

    path('ogrenciprojeler/', views.OgrenciProjeListView.as_view(), name="ogrenciproje_list"),
    path('ogrenciproje/<str:pk>/detail', views.OgrenciProjeDetailView.as_view(), name="ogrenciproje_detail"),

    path('myo/', views.MYOListView.as_view(), name="myo_list"),
    path('myo/<str:pk>/bolumler/', views.MYOBolumListView.as_view(), name="myo_bolum_list"),
    path('myo/bolum/<str:pk>/detail', views.MYOBolumDetailView.as_view(), name="myo_bolum_detail"),

    path('yorumlar/', views.YorumListView.as_view(), name="yorum_list"),
    path('kampusteyasam/', views.KampusteYasamListView.as_view(), name="kampuste_yasam"),
    path('eskisehirdeyasam/', views.EskisehirdeYasamTemplateView.as_view(), name="eskisehirde_yasam"),
    path('tercihgunleri/', views.TercihGunleriTemplateView.as_view(), name="tercih_gunleri"),
    path('tanitimfilmleri/', views.TanitimFilmleriTemplateView.as_view(), name="tanitim_filmleri"),

    path('puanlar/', views.PuanlarTemplateView.as_view(), name="puanlar"),

    path('estudeneyimle/', views.EstuDeneyimleTemplateView.as_view(), name="estu_deneyimle"),
    path('arastirmalisansustu/', views.EstuArastirmaLisansustuEgitimTemplateView.as_view(), name="estu_arastirma_lisansustu"),
]

siteapp/models.py
import sys
from django.db import models
from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
from ckeditor.fields import RichTextField
from django.utils.translation import ugettext_lazy as _
# Create your models here.

BIRIM_TUR_CHOICES = (
    ('fakulte', 'Fakülte'),
    ('enstitu', 'Enstitü'),
    ('kulup', 'Kulüp'),
)

ALTBIRIM_TUR_CHOICES = (
    ('sayisal', 'Sayısal'),
    ('esitagirlik', 'Eşit Ağırlık'),
    ('sozel', 'Sözel'),
)


def compressImage(uploadedImage):
    imageTemproary = Image.open(uploadedImage)
    outputIoStream = BytesIO()
    # imageTemproaryResized = imageTemproary.resize((1020, 573))
    imageTemproary.save(outputIoStream, format='JPEG', quality=30)
    outputIoStream.seek(0)
    uploadedImage = InMemoryUploadedFile(outputIoStream, 'ImageField', "%s.jpg" % uploadedImage.name.split('.')[0],
                                         'image/jpeg', sys.getsizeof(outputIoStream), None)
    return uploadedImage


class Fakulte(models.Model):
    baslik = models.CharField(max_length=100, verbose_name=_("Başlık"))
    kapakfoto = models.ImageField(upload_to="kapakfotolar/", blank=True, null=True, verbose_name=_("Kapak Fotoğrafı"))
    sunum = models.FileField(upload_to="sunumlar/", blank=True, null=True, verbose_name=_("Sunum"))

    def __str__(self):
        return self.baslik

    def save(self, *args, **kwargs):
        if not self.id and self.kapakfoto:
            self.kapakfoto = compressImage(self.kapakfoto)
        super(Fakulte, self).save(*args, **kwargs)

    class Meta:
        ordering = ('baslik',)
        verbose_name= _("Fakülte")
        verbose_name_plural= _("Fakülteler")


class Bolum(models.Model):
    baslik = models.CharField(max_length=100, verbose_name=_("Başlık"))
    tur = models.CharField(max_length=20, choices=ALTBIRIM_TUR_CHOICES, blank=True, null=True, verbose_name=_("Tür"))
    bolum = models.ForeignKey(Fakulte, on_delete=models.CASCADE, verbose_name=_("Bölüm"))
    yazi = RichTextField(blank=True, null=True, verbose_name=_("Yazı"))
    resim = models.ImageField(upload_to='altbirimler', blank=True, null=True, verbose_name=_("Resim"))
    thumbnail = models.ImageField(upload_to="thumbnails/", blank=True, null=True, verbose_name=_("Küçük Resim"))
    sunum = models.FileField(upload_to="sunumlar/", blank=True, null=True, verbose_name=_("Sunum"))
    telefon = models.CharField(max_length=50, blank=True, null=True, verbose_name=_("Telefon"))
    bolum_mail = models.CharField(max_length=200, blank=True, null=True, verbose_name=_("Bölüm Mail Adresi"))
    fakulte_mail = models.CharField(max_length=200, blank=True, null=True, verbose_name=_("Fakülte Mail Adresi"))
    web_sitesi = models.CharField(max_length=200, blank=True,null=True, verbose_name=_("Web Sitesi"))
    facebook_hesap = models.CharField(max_length=200, blank=True, null=True, verbose_name=_("Facebook Hesabı"))
    instagram_hesap = models.CharField(max_length=200, blank=True, null=True, verbose_name=_("İnstagram Hesabı"))
    twitter_hesap = models.CharField(max_length=200, blank=True, null=True, verbose_name=_("Twitter Hesabı"))
    youtube_hesap = models.CharField(max_length=200, blank=True, null=True, verbose_name=_("Youtube Hesabı"))
    linkedin_hesap = models.CharField(max_length=200, blank=True, null=True, verbose_name=_("Linkedin Hesabı"))
    youtube_video = models.TextField(blank=True, null=True, verbose_name=_("Youtube Videosu"))

    def __str__(self):
        return self.baslik

    def save(self, *args, **kwargs):
        if not self.id and self.resim:
            self.resim = compressImage(self.resim)
        if self.thumbnail:
            self.thumbnail = compressImage(self.thumbnail)

        super(Bolum, self).save(*args, **kwargs)
      
    class Meta:
        ordering = ('baslik',)
        verbose_name = _("Bölüm")
        verbose_name_plural = _("Bölümler")


class Enstitu(models.Model):
    baslik = models.CharField(max_length=100, verbose_name=_("Başlık"))
    sunum = models.FileField(upload_to="sunumlar/", blank=True, null=True, verbose_name=_("Sunum"))

    def __str__(self):
        return self.baslik

    class Meta:
        ordering = ('baslik',)
        verbose_name=_("Enstitü")
        verbose_name_plural=_("Enstitüler")


class AnaBilimDali(models.Model):
    baslik = models.CharField(max_length=100, verbose_name=_("Başlık"))
    tur = models.CharField(max_length=20, choices=ALTBIRIM_TUR_CHOICES, blank=True, null=True, verbose_name=_("Tür"))
    bolum = models.ForeignKey(Enstitu, on_delete=models.CASCADE, verbose_name=_("Bölüm"))
    yazi = RichTextField(blank=True, null=True, verbose_name=_("Yazı"))
    resim = models.ImageField(upload_to='anabilimdali', blank=True, null=True, verbose_name=_("Resim"))
    sunum = models.FileField(upload_to="sunumlar/", blank=True, null=True, verbose_name=_("Sunum"))
    telefon = models.CharField(max_length=50, blank=True, null=True, verbose_name=_("Telefon"))
    anabilimdali_mail = models.CharField(max_length=200, blank=True, null=True, verbose_name=_("Anabilim Dalı Email Adresi"))
    web_sitesi = models.CharField(max_length=200, blank=True,null=True, verbose_name=_("Web Sitesi"))
    enstitu_mail = models.CharField(max_length=200, blank=True, null=True, verbose_name=_("Enstitü Mail Adresi"))
    facebook_hesap = models.CharField(max_length=200, blank=True, null=True, verbose_name=_("Facebook Hesabı"))
    instagram_hesap = models.CharField(max_length=200, blank=True, null=True, verbose_name=_("İnstagram Hesabı"))
    twitter_hesap = models.CharField(max_length=200, blank=True, null=True, verbose_name=_("Twitter Hesabı"))
    youtube_hesap = models.CharField(max_length=200, blank=True, null=True, verbose_name=_("Youtube Hesabı"))
    linkedin_hesap = models.CharField(max_length=200, blank=True, null=True, verbose_name=_("Linkedin Hesabı"))
    youtube_video = models.TextField(blank=True, null=True, verbose_name=_("Youtube Videosu"))

    def __str__(self):
        return self.baslik

    def save(self, *args, **kwargs):
        if not self.id and self.resim:
            self.resim = compressImage(self.resim)
        super(AnaBilimDali, self).save(*args, **kwargs)

    class Meta:
        ordering = ('baslik',)
        verbose_name=_("Ana Bilim Dalı")
        verbose_name_plural=_("Ana Bilim Dalları")


class Kulup(models.Model):
    baslik = models.CharField(max_length=100, verbose_name=_("Başlık"))
    yazi = RichTextField(blank=True, null=True, verbose_name=_("Yazı"))
    paragraph = RichTextField(blank=True, null=True, verbose_name=_("Paragraf"))
    resim = models.ImageField(upload_to='kulupler', blank=True, null=True, verbose_name=_("Resim"))
    logo = models.ImageField(upload_to="kulupler/logolar/", blank=True, null=True, verbose_name=_("Logo"))
    kulup_baskani = models.CharField(max_length=150, blank=True, null=True, verbose_name=_("Kulüp Başkanı"))
    kulup_danismani = models.CharField(max_length=150, blank=True, null=True, verbose_name=_("Kulüp Danışmanı"))
    kulup_danismani_link = models.CharField(max_length=150, blank=True, null=True, verbose_name=_("Kulüp Danışmanı Link"))
    kulup_mail = models.CharField(max_length=200, blank=True, null=True, verbose_name=_("Kulüp Mail Adresi"))
    web_sitesi = models.CharField(max_length=200, blank=True,null=True, verbose_name=_("Web Sitesi"))
    facebook_hesap = models.CharField(max_length=200, blank=True, null=True, verbose_name=_("Facebook Hesabı"))
    instagram_hesap = models.CharField(max_length=200, blank=True, null=True, verbose_name=_("İnstagram Hesabı"))
    twitter_hesap = models.CharField(max_length=200, blank=True, null=True, verbose_name=_("Twitter Hesabı"))
    youtube_hesap = models.CharField(max_length=200, blank=True, null=True, verbose_name=_("Youtube Hesabı"))
    linkedin_hesap = models.CharField(max_length=200, blank=True, null=True, verbose_name=_("Linkedin Hesabı"))
    youtube_video = models.TextField(blank=True, null=True, verbose_name=_("Youtube Videosu"))
    

    def __str__(self):
        return self.baslik

    def save(self, *args, **kwargs):
        if not self.id and self.resim:
            self.resim = compressImage(self.resim)
        super(Kulup, self).save(*args, **kwargs)

    class Meta:
        ordering = ('baslik',)
        verbose_name=_("Kulüp")
        verbose_name_plural=_("Kulüpler")

YORUM_CHOICES = (
    ('ogretimuyesi', 'Öğretim Üyesi'),
    ('mezun', 'Mezun'),
    ('ogrenci', 'Öğrenci')
)

class Yorum(models.Model):
    adsoyad = models.CharField(max_length=100, verbose_name=_("Adı Soyadı"))
    yazi = RichTextField(blank=True, null=True, verbose_name=_("Yorum"))
    rol = models.CharField(max_length=100, blank=True, null=True, verbose_name=_("Rolü"))
    gorev = models.CharField(max_length=20, choices=YORUM_CHOICES, blank=True, null=True, verbose_name=_("Görevi"))
    fakulte =  models.ForeignKey(Fakulte, blank=True, null=True, on_delete=models.SET_NULL, verbose_name=_("Fakültesi"))
    bolum = models.ForeignKey(Bolum, blank=True, null=True, on_delete=models.SET_NULL, verbose_name=_("Bölümü"))
    resim = models.ImageField(upload_to="yorumlar", blank=True, null=True, verbose_name=_("Resim"))

    def __str__(self):
        return self.adsoyad

    def save(self, *args, **kwargs):
        if not self.id and self.resim:
            self.resim = compressImage(self.resim)
        super(Yorum, self).save(*args, **kwargs)

    class Meta:
        verbose_name=_("Yorum")
        verbose_name_plural=_("Yorumlar")

class MeslekYO(models.Model):
    baslik = models.CharField(max_length=100, verbose_name=_("Başlık"))
    kapakfoto = models.ImageField(upload_to="kapakfotolar/", blank=True, null=True, verbose_name=_("Kapak Fotoğrafı"))
    sunum = models.FileField(upload_to="sunumlar/", blank=True, null=True, verbose_name=_("Sunum"))

    def __str__(self):
        return self.baslik

    def save(self, *args, **kwargs):
        if not self.id and self.kapakfoto:

siteapp/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView
from .models import *


# Create your views here.

class FakulteListView(ListView):
    model = Fakulte
    template_name = "siteapp/fakulte/fakulteler.html"
    context_object_name = "fakulteler"


class FakulteBolumListView(DetailView):
    model = Fakulte
    template_name = "siteapp/fakulte/fakulte_bolumler.html"
    context_object_name = "active_fakulte"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['fakulteler'] = Fakulte.objects.all()
        return context


class BolumDetailView(DetailView):
    model = Bolum
    template_name = "siteapp/fakulte/bolum_detail.html"
    context_object_name = "active_bolum"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['fakulteler'] = Fakulte.objects.all()
        return context


class EnstituListView(ListView):
    model = Enstitu
    template_name = "siteapp/enstitu/enstituler.html"
    context_object_name = "enstituler"


class EnstituAnabilimDaliListView(DetailView):
    model = Enstitu
    template_name = "siteapp/enstitu/enstitu_anabilimdallari.html"
    context_object_name = "active_enstitu"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['enstituler'] = Enstitu.objects.all()
        return context


class AnabilimDaliDetailView(DetailView):
    model = AnaBilimDali
    template_name = "siteapp/enstitu/anabilimdali_detail.html"
    context_object_name = "active_abd"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['enstituler'] = Enstitu.objects.all()
        return context


class KulupListView(ListView):
    model = Kulup
    template_name = "siteapp/kulup/kulupler.html"
    context_object_name = "kulupler"


class KulupDetailView(DetailView):
    model = Kulup
    template_name = "siteapp/kulup/kulup_detail.html"
    context_object_name = "active_kulup"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['kulupler'] = Kulup.objects.all()
        return context


class BolumListView(ListView):
    model = Bolum
    template_name = "siteapp/bolum_list.html"
    context_object_name = "bolumler"


class MYOListView(ListView):
    model = MeslekYO
    template_name = "siteapp/myo/meslekyo.html"
    context_object_name = "myolar"


class MYOBolumListView(DetailView):
    model = MeslekYO
    template_name = "siteapp/myo/myo_bolumler.html"
    context_object_name = "active_myo"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['myolar'] = MeslekYO.objects.all()
        return context


class MYOBolumDetailView(DetailView):
    model = MYOBolum
    template_name = "siteapp/myo/myo_bolum_detail.html"
    context_object_name = "active_bolum"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['myolar'] = MeslekYO.objects.all()
        return context


class YorumListView(ListView):
    model = Yorum
    template_name = "siteapp/yorum_list.html"
    context_object_name = "yorumlar"
    paginate_by = 18

    def get_queryset(self):
        queryset = Yorum.objects.all()

        if self.request.GET.get('fakulte'):
            fakulte = Fakulte.objects.get(pk=self.request.GET.get('fakulte'))
            queryset = queryset.filter(fakulte=fakulte)
        if self.request.GET.get('bolum'):
            bolum = Bolum.objects.get(pk=self.request.GET.get('bolum'))
            queryset = queryset.filter(bolum=bolum)
        if self.request.GET.get('gorev'):
            queryset = queryset.filter(gorev=self.request.GET.get('gorev'))

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['fakulteler'] = Fakulte.objects.all()
        context['bolumler'] = Bolum.objects.all()
        context['gorevler'] = YORUM_CHOICES
        return context


class KampusteYasamListView(ListView):
    model = KampusGaleri
    template_name = "siteapp/kampuste_yasam.html"
    context_object_name = "resimler"


class PuanlarTemplateView(TemplateView):
    template_name = "siteapp/puanlar.html"


class OgrenciProjeListView(ListView):
    model = OgrenciProje
    template_name = "siteapp/ogrenciproje/ogrenciprojeler.html"
    context_object_name = "ogrenciprojeler"


class OgrenciProjeDetailView(DetailView):
    model = OgrenciProje
    template_name = "siteapp/ogrenciproje/ogrenciproje_detail.html"
    context_object_name = "active_proje"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ogrenciprojeler'] = OgrenciProje.objects.all()
        return context

    
class EskisehirdeYasamTemplateView(TemplateView):
    template_name = "siteapp/eskisehirde_yasam.html"


class TercihGunleriTemplateView(TemplateView):
    template_name = "siteapp/tercih_gunleri.html"


class TanitimFilmleriTemplateView(TemplateView):
    template_name = "siteapp/tanitim_filmleri.html"

class EstuDeneyimleTemplateView(TemplateView):
    template_name = "siteapp/estu_deneyimle.html"

class EstuArastirmaLisansustuEgitimTemplateView(TemplateView):
    template_name = "siteapp/estu_arastirma_lisansustu_egitim.html"

siteapp/templates/siteapp/enstitu/anabilimdali_detail.html
{% extends 'siteapp/base.html' %}

{% block extra-css %}
{{ block.super }}
<style>
    p {
        text-align: justify;
    }
</style>
{% endblock %}

{% block sidenav-links %}
{% for enstitu in enstituler %}
<a class="list-group-item list-group-item-action {% if enstitu == active_abd.bolum %}active{% endif %}"
    href="{% url 'siteapp:enstitu_abd_list' pk=enstitu.pk %}">{{ enstitu.baslik }}</a>
<div class="list-group pl-4 bg-secondary">
    {% for abd in enstitu.anabilimdali_set.all %}
    <a href="{% url 'siteapp:abd_detail' pk=abd.pk %}"
        class="list-group-item list-group-item-action {% if abd == active_abd %}active{% endif %}">{{ abd.baslik }}</a>
    {% endfor %}

</div>
{% endfor %}

{% endblock %}

{% block siteapp_content %}
<h1>{{ active_abd.baslik }}</h1>

{% if active_abd.resim %}
<img src="{{ active_abd.resim.url }}" alt="" class="w-75 mx-auto">
{% endif %}

{% autoescape off %}
{{ active_abd.yazi }}
{% endautoescape %}




{% if active_abd.telefon %}
<p>
    <a class="btn btn-disabled">
        <i class='fas fa-phone' style="font-size: 20pt;"></i>
        : {{active_abd.telefon}}

    </a>
</p>
{% endif %}


{% if active_abd.bolum_mail %}
<p>
    <a class="btn" href="mailto:{{active_abd.bolum_mail}}" target="_blank">
        <i class='fas fa-envelope' style="font-size: 20pt;"></i>
        : {{active_abd.bolum_mail}}
    </a>
</p>
{% endif %}
{% if active_abd.fakulte_mail %}
<p>
    <a class="btn" href="mailto:{{active_abd.fakulte_mail}}" target="_blank">
        <i class='fas fa-envelope' style="font-size: 20pt;"></i>
        : {{active_abd.fakulte_mail}}
    </a>
</p>
{% endif %}


{% if active_abd.web_sitesi %}
<p>
    <a class="btn" href="{{active_abd.web_sitesi}}" target="_blank">
        <i class='fas fa-globe-americas' style="font-size: 20pt;"></i>
        : {{active_abd.web_sitesi}}
    </a>
</p>
{% endif %}


{% if active_abd.facebook_hesap %}
<p>
    <a class="btn" href="{{active_abd.facebook_hesap}}" target="_blank">
        <i class='fab fa-facebook' style="font-size: 20pt;"></i>
        : {{active_abd.facebook_hesap}}
    </a>
</p>
{% endif %}


{% if active_abd.twitter_hesap %}
<p>
    <a class="btn" href="{{active_abd.twitter_hesap}}" target="_blank">
        <i class='fab fa-twitter' style="font-size: 20pt;"></i>
        : {{active_abd.twitter_hesap}}
    </a>
</p>
{% endif %}


{% if active_abd.instagram_hesap %}
<p>
    <a class="btn" href="{{active_abd.instagram_hesap}}" target="_blank" style="color:black;">
        <i class='fab fa-instagram' style="font-size: 20pt; "></i>
        : {{active_abd.instagram_hesap}}
    </a>
</p>
{% endif %}


{% if active_abd.youtube_hesap %}
<p>
    <a class="btn" href="{{active_abd.youtube_hesap}}" target="_blank" style="color:red;">
        <i class='fab fa-youtube' style="font-size: 20pt; "></i>
        : {{active_abd.youtube_hesap}}
    </a>
</p>
{% endif %}



{% if active_abd.linkedin_hesap %}
<p>
    <a class="btn" href="{{active_abd.linkedin_hesap}}" target="_blank">
        <i class='fab fa-linkedin' style="font-size: 20pt; "></i>
        : {{active_abd.linkedin_hesap}}
    </a>
</p>
{% endif %}

<br>
{% if active_abd.sunum %}
<div class="row justify-content-center">
    <a href="{{ active_abd.sunum.url }}" class="btn btn-outline-primary" target="_blank">Anabilimdalı sunum dosyası için
        tıklayınız.</a>
</div>
{% endif %}

<br>


{% if active_abd.youtube_video %}
{% autoescape off %}
{{ active_abd.youtube_video }}
{% endautoescape %}
{% endif %}

<br>
{% endblock %}

siteapp/templates/siteapp/enstitu/enstitu_anabilimdallari.html
{% extends 'siteapp/base.html' %}

{% block sidenav-links %}
    {% for enstitu in enstituler %}
        <a href="{% url 'siteapp:enstitu_abd_list' pk=enstitu.pk %}"
           class="list-group-item list-group-item-action {% if enstitu == active_enstitu %}active{% endif %}">{{ enstitu }}</a>
    {% endfor %}

{% endblock %}



{% block siteapp_content %}

    <h3>{{ active_enstitu.baslik }}</h3>
    <h5>Anabilim Dalları</h5>
    <ul>
        {% for abd in active_enstitu.anabilimdali_set.all %}
            <li><a href="{% url 'siteapp:abd_detail' pk=abd.pk %}">{{ abd.baslik }}</a></li>
        {% endfor %}

    </ul>
{% endblock %}

siteapp/templates/siteapp/enstitu/enstituler.html
{% extends 'siteapp/base.html' %}


{% block sidenav-links %}
    <a class="list-group-item list-group-item-action" href="{% url 'siteapp:fakulte_list' %}">
        Lisans Programları
    </a>
    <a class="list-group-item list-group-item-action" href="{% url 'siteapp:myo_list' %}">
        Önlisans Programları
    </a>
    <a class="list-group-item list-group-item-action active" href="{% url 'siteapp:enstitu_list' %}">
        Enstitüler
    </a>

    <a class="list-group-item list-group-item-action" href="{% url 'siteapp:kulup_list' %}">
        Kulüpler
    </a>

    <a class="list-group-item list-group-item-action" href="{% url 'siteapp:ogrenciproje_list' %}">
        Öğrenci Projeleri
    </a>
{% endblock %}


{% block siteapp_content %}

    <h3>Enstitüler</h3>

    <ul class="list-group">
        {% for enstitu in enstituler %}
            <li class="list-group-item">
                <a href="{% url 'siteapp:enstitu_abd_list' pk=enstitu.pk %}">{{ enstitu }}</a>
            </li>
            <ul>
            {% for abd in enstitu.anabilimdali_set.all %}
                <li class="list-group-item list-group-item-action">
                    <a href="{% url 'siteapp:abd_detail' pk=abd.pk %}">{{ abd.baslik }}</a>
                </li>
            {% endfor %}
            
            </ul>
        {% endfor %}

    </ul>

{% endblock %}