siteapp/urls.py
from django.urls import path
from . import views

app_name = "siteapp"

urlpatterns =[
    path('fakulteler/', views.FakulteListView.as_view(), name="fakulte_list"),
    path('fakulteler/<str:pk>/bolumler/', views.FakulteBolumListView.as_view(), name="fakulte_bolum_list"),
    path('bolum/<str:pk>/detail', views.BolumDetailView.as_view(), name="bolum_detail"),

    path('bolumler/', views.BolumListView.as_view(), name="bolum_list"),

    path('enstituler/', views.EnstituListView.as_view(), name="enstitu_list"),
    path('enstituler/<str:pk>/anabilimdali/', views.EnstituAnabilimDaliListView.as_view(), name="enstitu_abd_list"),
    path('anabilimdali/<str:pk>/detail', views.AnabilimDaliDetailView.as_view(), name="abd_detail"),

    path('kulupler/', views.KulupListView.as_view(), name="kulup_list"),
    path('kulup/<str:pk>/detail', views.KulupDetailView.as_view(), name="kulup_detail"),

    path('ogrenciprojeler/', views.OgrenciProjeListView.as_view(), name="ogrenciproje_list"),
    path('ogrenciproje/<str:pk>/detail', views.OgrenciProjeDetailView.as_view(), name="ogrenciproje_detail"),

    path('myo/', views.MYOListView.as_view(), name="myo_list"),
    path('myo/<str:pk>/bolumler/', views.MYOBolumListView.as_view(), name="myo_bolum_list"),
    path('myo/bolum/<str:pk>/detail', views.MYOBolumDetailView.as_view(), name="myo_bolum_detail"),

    path('yorumlar/', views.YorumListView.as_view(), name="yorum_list"),
    path('kampusteyasam/', views.KampusteYasamListView.as_view(), name="kampuste_yasam"),
    path('eskisehirdeyasam/', views.EskisehirdeYasamTemplateView.as_view(), name="eskisehirde_yasam"),
    path('tercihgunleri/', views.TercihGunleriTemplateView.as_view(), name="tercih_gunleri"),
    path('tanitimfilmleri/', views.TanitimFilmleriTemplateView.as_view(), name="tanitim_filmleri"),

    path('puanlar/', views.PuanlarTemplateView.as_view(), name="puanlar"),

    path('estudeneyimle/', views.EstuDeneyimleTemplateView.as_view(), name="estu_deneyimle"),
    path('arastirmalisansustu/', views.EstuArastirmaLisansustuEgitimTemplateView.as_view(), name="estu_arastirma_lisansustu"),
]

siteapp/forms.py
from django import forms
from .models import *


class YorumFilterForm(forms.Form):
    fakulte = forms.ModelChoiceField(queryset=Fakulte.objects.all(), required=False)
    bolum = forms.ModelChoiceField(queryset=Bolum.objects.all(), required=False)
    gorev = forms.ChoiceField(choices=YORUM_CHOICES, required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for f in self.fields.keys():
            self.fields[f].widget.attrs.update({'class':'form-control'})

        self.fields['fakulte'].label = "Fakülte"
        self.fields['bolum'].label = "Bölüm"
        self.fields['gorev'].label = "Öğrenci / Mezun / Öğretim Üyesi"

siteapp/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView
from .models import *


# Create your views here.

class FakulteListView(ListView):
    model = Fakulte
    template_name = "siteapp/fakulte/fakulteler.html"
    context_object_name = "fakulteler"


class FakulteBolumListView(DetailView):
    model = Fakulte
    template_name = "siteapp/fakulte/fakulte_bolumler.html"
    context_object_name = "active_fakulte"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['fakulteler'] = Fakulte.objects.all()
        return context


class BolumDetailView(DetailView):
    model = Bolum
    template_name = "siteapp/fakulte/bolum_detail.html"
    context_object_name = "active_bolum"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['fakulteler'] = Fakulte.objects.all()
        return context


class EnstituListView(ListView):
    model = Enstitu
    template_name = "siteapp/enstitu/enstituler.html"
    context_object_name = "enstituler"


class EnstituAnabilimDaliListView(DetailView):
    model = Enstitu
    template_name = "siteapp/enstitu/enstitu_anabilimdallari.html"
    context_object_name = "active_enstitu"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['enstituler'] = Enstitu.objects.all()
        return context


class AnabilimDaliDetailView(DetailView):
    model = AnaBilimDali
    template_name = "siteapp/enstitu/anabilimdali_detail.html"
    context_object_name = "active_abd"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['enstituler'] = Enstitu.objects.all()
        return context


class KulupListView(ListView):
    model = Kulup
    template_name = "siteapp/kulup/kulupler.html"
    context_object_name = "kulupler"


class KulupDetailView(DetailView):
    model = Kulup
    template_name = "siteapp/kulup/kulup_detail.html"
    context_object_name = "active_kulup"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['kulupler'] = Kulup.objects.all()
        return context


class BolumListView(ListView):
    model = Bolum
    template_name = "siteapp/bolum_list.html"
    context_object_name = "bolumler"


class MYOListView(ListView):
    model = MeslekYO
    template_name = "siteapp/myo/meslekyo.html"
    context_object_name = "myolar"


class MYOBolumListView(DetailView):
    model = MeslekYO
    template_name = "siteapp/myo/myo_bolumler.html"
    context_object_name = "active_myo"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['myolar'] = MeslekYO.objects.all()
        return context


class MYOBolumDetailView(DetailView):
    model = MYOBolum
    template_name = "siteapp/myo/myo_bolum_detail.html"
    context_object_name = "active_bolum"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['myolar'] = MeslekYO.objects.all()
        return context


class YorumListView(ListView):
    model = Yorum
    template_name = "siteapp/yorum_list.html"
    context_object_name = "yorumlar"
    paginate_by = 18

    def get_queryset(self):
        queryset = Yorum.objects.all()

        if self.request.GET.get('fakulte'):
            fakulte = Fakulte.objects.get(pk=self.request.GET.get('fakulte'))
            queryset = queryset.filter(fakulte=fakulte)
        if self.request.GET.get('bolum'):
            bolum = Bolum.objects.get(pk=self.request.GET.get('bolum'))
            queryset = queryset.filter(bolum=bolum)
        if self.request.GET.get('gorev'):
            queryset = queryset.filter(gorev=self.request.GET.get('gorev'))

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['fakulteler'] = Fakulte.objects.all()
        context['bolumler'] = Bolum.objects.all()
        context['gorevler'] = YORUM_CHOICES
        return context


class KampusteYasamListView(ListView):
    model = KampusGaleri
    template_name = "siteapp/kampuste_yasam.html"
    context_object_name = "resimler"


class PuanlarTemplateView(TemplateView):
    template_name = "siteapp/puanlar.html"


class OgrenciProjeListView(ListView):
    model = OgrenciProje
    template_name = "siteapp/ogrenciproje/ogrenciprojeler.html"
    context_object_name = "ogrenciprojeler"


class OgrenciProjeDetailView(DetailView):
    model = OgrenciProje
    template_name = "siteapp/ogrenciproje/ogrenciproje_detail.html"
    context_object_name = "active_proje"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ogrenciprojeler'] = OgrenciProje.objects.all()
        return context

    
class EskisehirdeYasamTemplateView(TemplateView):
    template_name = "siteapp/eskisehirde_yasam.html"


class TercihGunleriTemplateView(TemplateView):
    template_name = "siteapp/tercih_gunleri.html"


class TanitimFilmleriTemplateView(TemplateView):
    template_name = "siteapp/tanitim_filmleri.html"

class EstuDeneyimleTemplateView(TemplateView):
    template_name = "siteapp/estu_deneyimle.html"

class EstuArastirmaLisansustuEgitimTemplateView(TemplateView):
    template_name = "siteapp/estu_arastirma_lisansustu_egitim.html"

siteapp/templates/siteapp/myo/meslekyo.html
{% extends 'siteapp/base.html' %}


{% block sidenav-links %}
    <a class="list-group-item list-group-item-action" href="{% url 'siteapp:fakulte_list' %}">
        Lisans Programları
    </a>
    <a class="list-group-item list-group-item-action active" href="{% url 'siteapp:myo_list' %}">
        Önlisans Programları
    </a>

    <a class="list-group-item list-group-item-action" href="{% url 'siteapp:kulup_list' %}">
        Kulüpler
    </a>

    <a class="list-group-item list-group-item-action" href="{% url 'siteapp:ogrenciproje_list' %}">
        Öğrenci Projeleri
    </a>

{% endblock %}


{% block siteapp_content %}

    <h3>Önlisans Programları</h3>

    <ul class="list-group">
        {% for myo in myolar %}
            <li class="list-group-item">
                <a href="{% url 'siteapp:myo_bolum_list' pk=myo.pk %}">{{ myo }}</a>
            </li>
            <ul class="">
                {% for bolum in myo.myobolum_set.all %}
                    <li class="list-group-item list-group-item-action"><a
                            href="{% url 'siteapp:myo_bolum_detail' pk=bolum.pk %}">{{ bolum.baslik }}</a></li>
                {% endfor %}
            </ul>
        {% endfor %}

    </ul>

{% endblock %}

siteapp/templates/siteapp/myo/myo_bolum_detail.html
{% extends 'siteapp/base.html' %}

{% block extra-css %}
{{ block.super }}
<style>
    p {
        text-align: justify;
    }
</style>
{% if active_bolum.resim %}

<style>
    #siteContent {
        background-image: url("{{ active_bolum.resim.url }}");
        background-repeat: no-repeat;
        background-size: cover;
    }

    .image-overlay {
        background: rgba(255, 255, 255, 0.75);
        padding: 5px;
    }
</style>

{% endif %}
{% endblock %}

{% block sidenav-links %}
{% for myo in myolar %}
<a class="list-group-item list-group-item-action {% if myo == active_bolum.myo %}active{% endif %}"
    href="{% url 'siteapp:myo_bolum_list' pk=myo.pk %}">{{ myo.baslik }}</a>
<ul class="list-group bg-secondary fakulte pl-4">
    {% for bolum in myo.myobolum_set.all %}
    <a href="{% url 'siteapp:myo_bolum_detail' pk=bolum.pk %}"
        class="list-group-item list-group-item-action {% if bolum == active_bolum %}active{% endif %}">{{ bolum.baslik }}</a>
    </li>
    {% endfor %}
</ul>
{% endfor %}

{% endblock %}

{% block siteapp_content %}

<div class="image-overlay">
    <h1>{{ active_bolum.baslik }}</h1>

    {% if active_bolum.resim %}

    {% endif %}


    {% autoescape off %}
    {{ active_bolum.yazi }}
    {% endautoescape %}


    {% if active_bolum.sunum %}
    <br>
    <div class="row justify-content-center">
        <a href="{{ active_bolum.sunum.url }}" class="btn btn-outline-primary " target="_blank">Bölüm
            sunum dosyası için tıklayınız</a>
    </div>
    {% endif %}
</div>
{% endblock %}

siteapp/templates/siteapp/myo/myo_bolumler.html
{% extends 'siteapp/base_birim_bolumler.html' %}

{% block sidebar_kapak %}
    {% if active_myo.kapakfoto %}{{ active_myo.kapakfoto.url }}{% endif %}
{% endblock %}

{% block siteapp_content %}

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'siteapp:myo_list' %}">Önlisans Programları</a></li>
            <li class="breadcrumb-item active"><a
                    href="{% url 'siteapp:myo_bolum_list' pk=active_myo.pk %}">{{ active_myo }}</a></li>
        </ol>
    </nav>

    <h5>Bölümler</h5>
    <div class="row justify-content-center justify-content-md-start">
        {% for bolum in active_myo.myobolum_set.all %}

            <a class="bolum_btns" href="{% url 'siteapp:myo_bolum_detail' pk=bolum.pk %}"
               {% if bolum.thumbnail %}style="background-image: url({{ bolum.thumbnail.url }})" {% endif %}>
                <h2>{{ bolum.baslik }}</h2>
                <div class="bolum_btns_overlay">
                </div>
            </a>

        {% endfor %}
    </div>

    {% if active_myo.sunum %}
        <br>
        <div class="row justify-content-center">
            <a href="{{ active_myo.sunum.url }}" class="btn btn-outline-primary " target="_blank">Meslek Yüksek Okulu
                sunum dosyası için tıklayınız</a>
        </div>
    {% endif %}
{% endblock %}