siteapp/urls.py
from django.urls import path
from . import views

app_name = "siteapp"

urlpatterns =[
    path('fakulteler/', views.FakulteListView.as_view(), name="fakulte_list"),
    path('fakulteler/<str:pk>/bolumler/', views.FakulteBolumListView.as_view(), name="fakulte_bolum_list"),
    path('bolum/<str:pk>/detail', views.BolumDetailView.as_view(), name="bolum_detail"),

    path('bolumler/', views.BolumListView.as_view(), name="bolum_list"),

    path('enstituler/', views.EnstituListView.as_view(), name="enstitu_list"),
    path('enstituler/<str:pk>/anabilimdali/', views.EnstituAnabilimDaliListView.as_view(), name="enstitu_abd_list"),
    path('anabilimdali/<str:pk>/detail', views.AnabilimDaliDetailView.as_view(), name="abd_detail"),

    path('kulupler/', views.KulupListView.as_view(), name="kulup_list"),
    path('kulup/<str:pk>/detail', views.KulupDetailView.as_view(), name="kulup_detail"),

    path('ogrenciprojeler/', views.OgrenciProjeListView.as_view(), name="ogrenciproje_list"),
    path('ogrenciproje/<str:pk>/detail', views.OgrenciProjeDetailView.as_view(), name="ogrenciproje_detail"),

    path('myo/', views.MYOListView.as_view(), name="myo_list"),
    path('myo/<str:pk>/bolumler/', views.MYOBolumListView.as_view(), name="myo_bolum_list"),
    path('myo/bolum/<str:pk>/detail', views.MYOBolumDetailView.as_view(), name="myo_bolum_detail"),

    path('yorumlar/', views.YorumListView.as_view(), name="yorum_list"),
    path('kampusteyasam/', views.KampusteYasamListView.as_view(), name="kampuste_yasam"),
    path('eskisehirdeyasam/', views.EskisehirdeYasamTemplateView.as_view(), name="eskisehirde_yasam"),
    path('tercihgunleri/', views.TercihGunleriTemplateView.as_view(), name="tercih_gunleri"),
    path('tanitimfilmleri/', views.TanitimFilmleriTemplateView.as_view(), name="tanitim_filmleri"),

    path('puanlar/', views.PuanlarTemplateView.as_view(), name="puanlar"),

    path('estudeneyimle/', views.EstuDeneyimleTemplateView.as_view(), name="estu_deneyimle"),
    path('arastirmalisansustu/', views.EstuArastirmaLisansustuEgitimTemplateView.as_view(), name="estu_arastirma_lisansustu"),
]

templates/base.html
<!doctype html>
{% load static %}
{% load i18n %}
<html lang="{% block lang-code %}tr{% endblock lang-code %}">
<head>
    {% block meta-settings %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
    {% endblock meta-settings %}

    <title>
        {% trans 'Eskişehir Teknik Üniversitesi' %} |
        {% block site-title %}
        {% endblock site-title %}
    </title>

    {% block bootstrap %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    {% endblock bootstrap %}
    

    
    
    {% block fontawesome %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
    integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    {% endblock fontawesome %}
        
    
    {% block custom-css %}
    <link rel="stylesheet" href="{% static 'css/genel.css' %}">
    {% endblock custom-css %}
    
    
    
    {% block extra-css %}
    
    {% endblock extra-css %}
    
    
</head>

<body>
    
    <div class="wrapper">
        
        
        <div class="page-content-wrapper">
            {% block navbar %}
            <nav class="navbar navbar-expand-lg {% block navbar-class %}navbar-dark{% endblock %} navbar-bg fixed-top"
            id="navbar-main">
            {% block navbar-logo %}
            <a class="navbar-brand" href="{% url 'home' %}">
                ESTÜ
            </a>
            {% endblock %}
            <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                {% block navbar_links-left %}
                
                {% endblock %}
            </ul>
            <ul class="navbar-nav ml-auto">
                {% block navbar_links-right %}
                
                {% endblock %}
            </ul>
            
        </div>
    </nav>
    {% endblock %}
    
    
    <div class="content" style="min-height:90vh;">
        {% block content %}
        
        {% endblock %}
    </div>
</div>

</div>

{% block footer %}

<!-- Footer -->
<footer class="page-footer font-small bg-dark pt-4" id="footer">
    
    <!-- Footer Links -->
    <div class="container-fluid text-center text-md-left">
        
        <!-- Grid row -->
        <div class="row">
            <div class="col"></div>
            
            <div class="col-3 col-md-1">
                <svg width="100%" height="100%" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg"
                class="footer-logo">
                
                
                <polygon points="0, 50, 20, 70, 30, 60, 20, 50, 40, 30, 30, 20"
                fill="#ffffff" fill-opacity="0.8" stroke=" gray" stroke-width=0
                stroke-opacity="0.3"/>
                
                <polygon points="40, 10, 50, 20, 60, 10, 50, 0"
                fill="#ffffff" fill-opacity="0.8" stroke=" gray" stroke-width="0"
                stroke-opacity="0.3"/>
                
                
                <polygon points="30, 60, 40, 70, 80, 30, 70, 20"
                fill="#ffffff" fill-opacity="0.8" stroke=" gray" stroke-width="0"
                stroke-opacity="0.3"/>
                
                <polygon points="30, 80, 50, 100, 80, 70, 70, 60, 50, 80, 40, 70"
                fill="#ffffff" fill-opacity="0.8" stroke=" gray" stroke-width="0"
                stroke-opacity="0.3"/>
                
                <polygon fill="#ffffff" fill-opacity="0.8" stroke=" gray" stroke-width="0"
                stroke-opacity="0.3"
                points="80, 50, 90, 60, 100, 50, 90, 40"/>
                
            </svg>
        </div>
        <!-- Grid column -->
        <div class="col-md-6 mt-md-0 mt-3 text-center">
            
            <!-- Content -->
            <p>Adres: Eskişehir Teknik Üniversitesi İki Eylül Kampüsü 26555 Tepebaşı / ESKİŞEHİR</p>
            <p>Santral: +90 222 321 35 50</p>
            <p>Faks: +90 222 211 59 01</p>
            <p>Web: <a href="http://www.eskisehir.edu.tr" target="_blank">www.eskisehir.edu.tr</a></p>
        </div>
        <!-- Grid column -->
        
        <hr class="clearfix w-100 d-md-none pb-3">
        
        <!-- Grid column -->
        <div class="col-md-3 mb-md-0 mb-3">
            
            <!-- Links -->
            <ul class="nav" id="socialmedia">
                <li class="nav-item">
                    <a class="nav-link" href="https://www.facebook.com/eskisehirteknikuniv" target="_blank"><i
                        class='fab fa-facebook-f'></i></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="https://twitter.com/esteknikuniv" target="_blank"><i
                            class="fab fa-twitter"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="http://instagram.com/eskisehirteknikuniv" target="_blank"><i
                                class="fab fa-instagram"></i></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="https://www.youtube.com/channel/UC-oGylb9E16KNqMnTP_kDoA"
                                target="_blank"><i
                                class="fab fa-youtube"></i></a>
                            </li>
                            
                        </ul>
                        
                    </div>
                    <!-- Grid column -->
                    
                    <div class="col"></div>
                </div>
                <!-- Grid row -->
                
            </div>
            <!-- Footer Links -->
            
            
        </footer>
        <!-- Footer -->
        
        
        {% endblock footer %}
        
        
        {% block jquery %}

        
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        {% endblock jquery %}
            
        {% block bootstrap-script %}
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        {% endblock bootstrap-script %}
                
{% block language_script %}
<script>
    function set_lang(lang) {
        $('#id_language').val(lang);
        $('#form_setlang').submit();
    }
    </script>
{% endblock language_script %}

{% block scripts %}

{% endblock scripts %}

{% block custom-scripts %}

{% endblock custom-scripts %}
</body>
</html>

templates/base_site.html
{% extends 'base.html' %}

{% block navbar_links-left %}
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
           aria-haspopup="true" aria-expanded="false">
            Programlar
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'siteapp:fakulte_list' %}">Lisans Programları</a>
            <a class="dropdown-item" href="{% url 'siteapp:myo_list' %}">Önlisans Programları</a>
            <a class="dropdown-item" href="{% url 'siteapp:kulup_list' %}">Kulüpler</a>
        </div>
    </li>

    <li class="nav-item"><a href="{% url 'siteapp:puanlar' %}" class="nav-link">Puanlar</a></li>
    <li class="nav-item"><a href="{% url 'siteapp:ogrenciproje_list' %}" class="nav-link">Öğrenci Projeleri</a></li>
{% endblock %}

{% block navbar_links-right %}

    <a href="mailto:kurumsaliletisim@eskisehir.edu.tr" target="_blank" class="btn btn-action" style="margin:0; font-size: 16px;">Soru Sorun</a>
{% endblock %}

templates/home2.html
{% extends 'base_site.html' %}
{% load static %}

{% block navbar-class %}
    navbar-light
{% endblock %}


{% block content %}


    <section id="intro">
        <div class="intro-container">
            <div class="carousel slide carousel-fade" id="introCarousel" data-ride="carousel">
                <ol class="carousel-indicators"></ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <div class="carousel-background"><img src="{% static 'img/slider2.JPG' %}"
                                                              alt="Eskişehir Teknik Üniversitesi"></div>
                        <div class="carousel-container">
                            <div class="carousel-content" style="width: 100%;">
                                <svg width="20%" height="20%" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">


                                    <polygon points="0, 50, 20, 70, 30, 60, 20, 50, 40, 30, 30, 20"
                                             fill="#870c0b" fill-opacity="0.8" stroke=" gray" stroke-width=0
                                             stroke-opacity="0.3"/>

                                    <polygon points="40, 10, 50, 20, 60, 10, 50, 0"
                                             fill="#870c0b" fill-opacity="0.8" stroke=" gray" stroke-width="0"
                                             stroke-opacity="0.3"/>


                                    <polygon points="30, 60, 40, 70, 80, 30, 70, 20"
                                             fill="#870c0b" fill-opacity="0.8" stroke=" gray" stroke-width="0"
                                             stroke-opacity="0.3"/>

                                    <polygon points="30, 80, 50, 100, 80, 70, 70, 60, 50, 80, 40, 70"
                                             fill="#870c0b" fill-opacity="0.8" stroke=" gray" stroke-width="0"
                                             stroke-opacity="0.3"/>

                                    <polygon fill="#870c0b" fill-opacity="0.8" stroke=" gray" stroke-width="0"
                                             stroke-opacity="0.3"
                                             points="80, 50, 90, 60, 100, 50, 90, 40"/>

                                </svg>

                                <h2>Eskişehir Teknik Üniversitesi</h2>
                                <p>Gelecek için inovasyon</p>
                                <div class="row" style="padding-left: 8%;">

                                    <a class="col-2 site_btns" href="">
                                        Kampüste Yaşam

                                    </a>
                                    <a class="col-2 site_btns" href="{% url 'siteapp:fakulte_list' %}">
                                        Fakülteler

                                    </a>
                                    <a class="col-2 site_btns" href="{% url 'siteapp:enstitu_list' %}">
                                        Enstitüler

                                    </a>
                                    <a class="col-2 site_btns" href="{% url 'siteapp:bolum_list' %}">
                                        Bölümler

                                    </a>
                                    <a class="col-2 site_btns" href="{% url 'siteapp:kulup_list' %}">
                                        Kulüpler

                                    </a>
                                    <a class="col-2 site_btns" href="">
                                        Puanlar

                                    </a>
                                </div>
                            </div>
                        </div>

                    </div>

                </div>
            </div>
            <a class="carousel-control-prev" href="#introCarousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon ion-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Önceki</span>
            </a>

            <a class="carousel-control-next" href="#introCarousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon ion-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Sonraki</span>
            </a>

        </div>
        </div>
    </section>


    <section class="bg-light">
        <div class="container">
            <h1>Rektörün Mesajı</h1>

            <div class="row">
                <div class="col-12 col-lg-6">
                    <iframe width="100%" height="300" src="https://www.youtube.com/embed/wQVLW5TVCeo" frameborder="0"
                            allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                            allowfullscreen style=""></iframe>
                </div>
                <div class="col-12 text-justify" style="align-content: center; line-height: 1.5;">
                    <p>Sevgili Gençler,</p>

                    <p>
                        Hayatınızın en önemli dönüm noktalarından birindesiniz. Uzun ve yorucu bir maratonu geride
                        bıraktınız. Emeklerinizin karşılığını alacağınız, yaşamınıza yön vereceğiniz, kendiniz ve
                        aileniz için yeni bir hayat inşa edeceğiniz önemli bir noktadasınız.
                    </p>

                    <p>
                        Şüphesiz doğru tercih yapmak sadece sizin değil Ülkemizin geleceği, yarınları için de önemli.
                    </p>

                    <p>
                        Tercih yaparken içinde bulunduğunuz dünyayı çok iyi anlamanız gerekiyor. Günümüzde teknoloji ve
                        bilim alanında yaşanan gelişmeler hayatın her alanını daha önce eşi benzeri görülmemiş şekilde
                        değiştirdi. Artık bilgiye ulaşmak bundan 10 yıl öncesine göre oldukça kolay.
                    </p>

                    <p>
                        Ancak değişen şartlar içerisinde sadece bilgiye ulaşmak değil, ulaştığı bilgiyi sosyal ve
                        mesleki beceriler ile birleştirmek aynı zamanda bilgiyi analitik süreçlerden geçirmek,
                        sorgulamak ve uygulama yapabilme becerisine sahip olmak da bir o kadar önemli.
                    </p>

                    <p>
                        Çünkü değişen dünya şartlarında her alanda büyük bir rekabet yaşanıyor. Bu rekabet teknolojiden
                        bilime her alanda insanlığın sınırlarını geliştiriyor, değiştiriyor. Artık sadece belli bir
                        konuda uzman olmak yeterli değil. Disiplinlerarası çalışmalarda yer alabilmek ve farklı
                        alanlardaki bakış açılarının bütünleştirilerek uygulanmasını sağlamak da üretilenlere değer
                        katıyor.
                    </p>

                    <p>
                        Makinelerin yapay zekâ ile düşünmeye başladığı, bilgi ve iletişimin ışık hızı ile yayıldığı,
                        hayatımıza dokunan tüm alanlarda insan öğesinin ön plana çıktığı bir dönemdeyiz. Bu dönemde
                        mesleklerin yapıları sorgulanıyor, hatta yeniden tanımlanıyor.
                    </p>

                    <p>
                        Eskişehir Teknik Üniversitesi, “Bir Gelecek Üniversitesi” olarak sizleri bu değişen ve dönüşen
                        dünyada sadece yarınlara hazırlamak için değil, yarınlara taşımak için de hazır. Bizler
                        küreselleşen dünyada değişen rekabet ortamında kuralları ve standartları belirleyen bireyler
                        yetiştirmeyi kendimize hedef edindik. Üniversitemiz bu yüzden öğrencilerine sadece eğitim
                        aldıkları alanda değil sosyal, kültürel ve sanatsal alanda da yetkinlik kazandırarak hayata
                        hazırlıyor. Yükseköğretimde kalite konusunda uluslararası standartların üstünde yer almayı
                        kendine hedef edinmiş olan Eskişehir Teknik Üniversitesi güçlü akademik kadrosu, altyapı
                        olanakları, geniş kampüs imkanları, aktif öğrenci kulüpleri, spor olanakları, öğrenci projeleri
                        ve vizyonu ile size geleceği vadediyor.
                    </p>

                    <p>
                        Bu dönemde vereceğiniz kararı etkileyen en önemli iki unsur hiç kuşkusuz Üniversite ve şehir
                        tercihi olacaktır. Üniversitemizin sizlere kazandıracağı değerlerin gelecekte sizler için
                        mutluluk ve gurur kaynağı olacağı konusunda hiçbir şüphem yok. Dünyanın en güvenli şehirleri
                        arasında yer alan Eskişehir ise sizlerin sosyal, kültürel ve bilimsel ihtiyaçlarına cevap
                        verirken, ayrıcalıklı yaşam standartlarını da sizlere sunuyor olacaktır. Bir hoca ve bilim
                        insanı olarak tüm bu nedenlerle Eskişehir Teknik Üniversitesi’nin gönül rahatlığı ile tercih
                        edilmesi gerektiğini söylemem yanlış olmayacaktır. Sizler için önemli ve zor olan karar
                        döneminde sizlere her konuda yardımcı olmaya hazır olduğumuzu belirtmek isterim.
                    </p>


                    <p>
                        Sevgili Gençler; Sizden beklentimiz, hem öğrencilik yıllarınızda hem de meslek yaşamınızda
                        tutkunuzu asla kaybetmemeniz, seçeceğiniz yolda emin adımlarla ilerlemeniz, mezuniyetinizle
                        birlikte mesleki bilgi ve becerilerle donanmış ülkesine ve dünyaya hizmet edecek iyi birer insan
                        olarak hayata atılmanızdır. Sağlıklı, mutlu ve başarılı bir öğrencilik yaşamı geçirmeniz
                        dilekleriyle hepinizi sevgiyle kucaklıyorum.
                    </p>

                    <p>
                        Hayattaki tercihlerinizin her zaman “iyi ki” dedirtmesi dileklerimle…
                    </p>

                    <p>
                        Prof. Dr. Tuncay Döğeroğlu <br>
                        Rektör
                    </p>


                </div>
            </div>

        </div>
    </section>




{% endblock %}

{% block scripts %}
    <script>

        $(document).ready(function () {
            var navbar = $('#navbar-main');
            navbar.addClass('navbar-light');
            $(window).scroll(function () {
                if ($(window).scrollTop() > 300) {
                    navbar.removeClass('transparent').removeClass('navbar-light').addClass('navbar-dark');
                } else {
                    navbar.addClass('transparent').removeClass('navbar-dark').addClass('navbar-light');
                }
            });
        });

        var navbar = $('#navbar-main');
        navbar.addClass('transparent');
        $(window).scroll(function () {
            var intro = $('#intro');
            var hT = intro.offset().top,
                hH = intro.outerHeight(),
                wH = $(window).height(),
                wS = $(this).scrollTop();
            if (wS > navbar.offset().top + navbar.height()) {
                navbar.removeClass('transparent')
            } else {
                navbar.addClass('transparent');
            }
        });
    </script>
{% endblock %}

templates/home_intro_link.html
<div class="col m-2 p-0">
    <div class="card site-links p-0 p-md-1 p-lg-2">
        <a class="btn"
        href="{{link_url}}">
        {{link_text}}
    </a>
    </div>
</div>